; AL highlights for Zed/tree-sitter
; AUTO-GENERATED - DO NOT EDIT (copied by AL Tree Sitter)

(comment) @comment
(string) @string
(integer) @number

; All keyword highlighting is provided by the generator via this placeholder.
; This ensures categorization follows the TextMate grammar scopes (storage type, built-in type, etc.)
(kw_action) @keyword.control
(kw_actionref) @keyword.control
(kw_array) @keyword.control
(kw_asserterror) @keyword.control
(kw_auditcategory) @keyword.control
(kw_automation) @keyword.control
(kw_begin) @keyword.control
(kw_biginteger) @keyword.control
(kw_bigtext) @keyword.control
(kw_blob) @keyword.control
(kw_boolean) @keyword.control
(kw_break) @keyword.control
(kw_byte) @keyword.control
(kw_case) @keyword.control
(kw_char) @keyword.control
(kw_clienttype) @keyword.control
(kw_code) @keyword.control
(kw_codeunit) @keyword.control
(kw_completiontriggererrorlevel) @keyword.control
(kw_connectiontype) @keyword.control
(kw_continue) @keyword.control
(kw_controladdin) @keyword.control
(kw_cookie) @keyword.control
(kw_customaction) @keyword.control
(kw_database) @keyword.control
(kw_dataclassification) @keyword.control
(kw_datascope) @keyword.control
(kw_datatransfer) @keyword.control
(kw_date) @keyword.control
(kw_dateformula) @keyword.control
(kw_datetime) @keyword.control
(kw_decimal) @keyword.control
(kw_defaultlayout) @keyword.control
(kw_dialog) @keyword.control
(kw_dictionary) @keyword.control
(kw_do) @keyword.control
(kw_dotnet) @keyword.control
(kw_dotnetassembly) @keyword.control
(kw_dotnettypedeclaration) @keyword.control
(kw_downto) @keyword.control
(kw_duration) @keyword.control
(kw_else) @keyword.control
(kw_end) @keyword.control
(kw_entitlement) @keyword.control
(kw_enum) @keyword.control
(kw_enumextension) @keyword.control
(kw_errorinfo) @keyword.control
(kw_errortype) @keyword.control
(kw_event) @keyword.control
(kw_executioncontext) @keyword.control
(kw_executionmode) @keyword.control
(kw_exit) @keyword.control
(kw_fieldclass) @keyword.control
(kw_fieldref) @keyword.control
(kw_fieldtype) @keyword.control
(kw_file) @keyword.control
(kw_fileupload) @keyword.control
(kw_fileuploadaction) @keyword.control
(kw_filterpagebuilder) @keyword.control
(kw_for) @keyword.control
(kw_foreach) @keyword.control
(kw_function) @keyword.control
(kw_guid) @keyword.control
(kw_httpclient) @keyword.control
(kw_httpcontent) @keyword.control
(kw_httpheaders) @keyword.control
(kw_httprequestmessage) @keyword.control
(kw_httprequesttype) @keyword.control
(kw_httpresponsemessage) @keyword.control
(kw_if) @keyword.control
(kw_in) @keyword.control
(kw_indataset) @keyword.control
(kw_instream) @keyword.control
(kw_integer) @keyword.control
(kw_interface) @keyword.control
(kw_internal) @keyword.control
(kw_isolationlevel) @keyword.control
(kw_joker) @keyword.control
(kw_jsonarray) @keyword.control
(kw_jsonobject) @keyword.control
(kw_jsontoken) @keyword.control
(kw_jsonvalue) @keyword.control
(kw_keyref) @keyword.control
(kw_list) @keyword.control
(kw_local) @keyword.control
(kw_media) @keyword.control
(kw_mediaset) @keyword.control
(kw_moduledependencyinfo) @keyword.control
(kw_moduleinfo) @keyword.control
(kw_none) @keyword.control
(kw_notification) @keyword.control
(kw_notificationscope) @keyword.control
(kw_objecttype) @keyword.control
(kw_of) @keyword.control
(kw_option) @keyword.control
(kw_outstream) @keyword.control
(kw_page) @keyword.control
(kw_pagebackgroundtaskerrorlevel) @keyword.control
(kw_pagecustomization) @keyword.control
(kw_pageextension) @keyword.control
(kw_pageresult) @keyword.control
(kw_pagestyle) @keyword.control
(kw_permissionset) @keyword.control
(kw_permissionsetextension) @keyword.control
(kw_procedure) @keyword.control
(kw_profile) @keyword.control
(kw_profileextension) @keyword.control
(kw_program) @keyword.control
(kw_protected) @keyword.control
(kw_query) @keyword.control
(kw_record) @keyword.control
(kw_recordid) @keyword.control
(kw_recordref) @keyword.control
(kw_repeat) @keyword.control
(kw_report) @keyword.control
(kw_reportextension) @keyword.control
(kw_reportformat) @keyword.control
(kw_runonclient) @keyword.control
(kw_secrettext) @keyword.control
(kw_securityfilter) @keyword.control
(kw_securityfiltering) @keyword.control
(kw_securityoperationresult) @keyword.control
(kw_sessionsettings) @keyword.control
(kw_suppressdispose) @keyword.control
(kw_systemaction) @keyword.control
(kw_table) @keyword.control
(kw_tableconnectiontype) @keyword.control
(kw_tableextension) @keyword.control
(kw_tablefilter) @keyword.control
(kw_temporary) @keyword.control
(kw_testaction) @keyword.control
(kw_testfield) @keyword.control
(kw_testfilterfield) @keyword.control
(kw_testhttprequestmessage) @keyword.control
(kw_testhttpresponsemessage) @keyword.control
(kw_testpage) @keyword.control
(kw_testpermissions) @keyword.control
(kw_testrequestpage) @keyword.control
(kw_text) @keyword.control
(kw_textbuilder) @keyword.control
(kw_textconst) @keyword.control
(kw_textencoding) @keyword.control
(kw_then) @keyword.control
(kw_time) @keyword.control
(kw_to) @keyword.control
(kw_transactionmodel) @keyword.control
(kw_transactiontype) @keyword.control
(kw_trigger) @keyword.control
(kw_until) @keyword.control
(kw_value) @keyword.control
(kw_var) @keyword.control
(kw_variant) @keyword.control
(kw_verbosity) @keyword.control
(kw_version) @keyword.control
(kw_view) @keyword.control
(kw_views) @keyword.control
(kw_webserviceactioncontext) @keyword.control
(kw_webserviceactionresultcode) @keyword.control
(kw_while) @keyword.control
(kw_with) @keyword.control
(kw_withevents) @keyword.control
(kw_xmlattribute) @keyword.control
(kw_xmlattributecollection) @keyword.control
(kw_xmlcdata) @keyword.control
(kw_xmlcomment) @keyword.control
(kw_xmldeclaration) @keyword.control
(kw_xmldocument) @keyword.control
(kw_xmldocumenttype) @keyword.control
(kw_xmlelement) @keyword.control
(kw_xmlnamespacemanager) @keyword.control
(kw_xmlnametable) @keyword.control
(kw_xmlnode) @keyword.control
(kw_xmlnodelist) @keyword.control
(kw_xmlport) @keyword.control
(kw_xmlprocessinginstruction) @keyword.control
(kw_xmlreadoptions) @keyword.control
(kw_xmltext) @keyword.control
(kw_xmlwriteoptions) @keyword.control
(kw_codeunit) @keyword.storage.type
(kw_controladdin) @keyword.storage.type
(kw_dotnet) @keyword.storage.type
(kw_entitlement) @keyword.storage.type
(kw_enum) @keyword.storage.type
(kw_enumextension) @keyword.storage.type
(kw_interface) @keyword.storage.type
(kw_page) @keyword.storage.type
(kw_pagecustomization) @keyword.storage.type
(kw_pageextension) @keyword.storage.type
(kw_permissionset) @keyword.storage.type
(kw_permissionsetextension) @keyword.storage.type
(kw_profile) @keyword.storage.type
(kw_profileextension) @keyword.storage.type
(kw_query) @keyword.storage.type
(kw_report) @keyword.storage.type
(kw_reportextension) @keyword.storage.type
(kw_table) @keyword.storage.type
(kw_tableextension) @keyword.storage.type
(kw_value) @keyword.storage.type
(kw_xmlport) @keyword.storage.type
(kw_action) @type.builtin
(kw_actionref) @type.builtin
(kw_array) @type.builtin
(kw_auditcategory) @type.builtin
(kw_automation) @type.builtin
(kw_biginteger) @type.builtin
(kw_bigtext) @type.builtin
(kw_blob) @type.builtin
(kw_boolean) @type.builtin
(kw_byte) @type.builtin
(kw_char) @type.builtin
(kw_clienttype) @type.builtin
(kw_code) @type.builtin
(kw_codeunit) @type.builtin
(kw_completiontriggererrorlevel) @type.builtin
(kw_connectiontype) @type.builtin
(kw_cookie) @type.builtin
(kw_customaction) @type.builtin
(kw_database) @type.builtin
(kw_dataclassification) @type.builtin
(kw_datascope) @type.builtin
(kw_datatransfer) @type.builtin
(kw_date) @type.builtin
(kw_dateformula) @type.builtin
(kw_datetime) @type.builtin
(kw_decimal) @type.builtin
(kw_defaultlayout) @type.builtin
(kw_dialog) @type.builtin
(kw_dictionary) @type.builtin
(kw_dotnet) @type.builtin
(kw_dotnetassembly) @type.builtin
(kw_dotnettypedeclaration) @type.builtin
(kw_duration) @type.builtin
(kw_enum) @type.builtin
(kw_errorinfo) @type.builtin
(kw_errortype) @type.builtin
(kw_executioncontext) @type.builtin
(kw_executionmode) @type.builtin
(kw_fieldclass) @type.builtin
(kw_fieldref) @type.builtin
(kw_fieldtype) @type.builtin
(kw_file) @type.builtin
(kw_fileupload) @type.builtin
(kw_fileuploadaction) @type.builtin
(kw_filterpagebuilder) @type.builtin
(kw_guid) @type.builtin
(kw_httpclient) @type.builtin
(kw_httpcontent) @type.builtin
(kw_httpheaders) @type.builtin
(kw_httprequestmessage) @type.builtin
(kw_httprequesttype) @type.builtin
(kw_httpresponsemessage) @type.builtin
(kw_instream) @type.builtin
(kw_integer) @type.builtin
(kw_interface) @type.builtin
(kw_isolationlevel) @type.builtin
(kw_joker) @type.builtin
(kw_jsonarray) @type.builtin
(kw_jsonobject) @type.builtin
(kw_jsontoken) @type.builtin
(kw_jsonvalue) @type.builtin
(kw_keyref) @type.builtin
(kw_list) @type.builtin
(kw_media) @type.builtin
(kw_mediaset) @type.builtin
(kw_moduledependencyinfo) @type.builtin
(kw_moduleinfo) @type.builtin
(kw_none) @type.builtin
(kw_notification) @type.builtin
(kw_notificationscope) @type.builtin
(kw_objecttype) @type.builtin
(kw_option) @type.builtin
(kw_outstream) @type.builtin
(kw_page) @type.builtin
(kw_pagebackgroundtaskerrorlevel) @type.builtin
(kw_pageresult) @type.builtin
(kw_pagestyle) @type.builtin
(kw_query) @type.builtin
(kw_record) @type.builtin
(kw_recordid) @type.builtin
(kw_recordref) @type.builtin
(kw_report) @type.builtin
(kw_reportformat) @type.builtin
(kw_secrettext) @type.builtin
(kw_securityfilter) @type.builtin
(kw_securityfiltering) @type.builtin
(kw_securityoperationresult) @type.builtin
(kw_sessionsettings) @type.builtin
(kw_systemaction) @type.builtin
(kw_table) @type.builtin
(kw_tableconnectiontype) @type.builtin
(kw_tablefilter) @type.builtin
(kw_testaction) @type.builtin
(kw_testfield) @type.builtin
(kw_testfilterfield) @type.builtin
(kw_testhttprequestmessage) @type.builtin
(kw_testhttpresponsemessage) @type.builtin
(kw_testpage) @type.builtin
(kw_testpermissions) @type.builtin
(kw_testrequestpage) @type.builtin
(kw_text) @type.builtin
(kw_textbuilder) @type.builtin
(kw_textconst) @type.builtin
(kw_textencoding) @type.builtin
(kw_time) @type.builtin
(kw_transactionmodel) @type.builtin
(kw_transactiontype) @type.builtin
(kw_variant) @type.builtin
(kw_verbosity) @type.builtin
(kw_version) @type.builtin
(kw_view) @type.builtin
(kw_views) @type.builtin
(kw_webserviceactioncontext) @type.builtin
(kw_webserviceactionresultcode) @type.builtin
(kw_xmlattribute) @type.builtin
(kw_xmlattributecollection) @type.builtin
(kw_xmlcdata) @type.builtin
(kw_xmlcomment) @type.builtin
(kw_xmldeclaration) @type.builtin
(kw_xmldocument) @type.builtin
(kw_xmldocumenttype) @type.builtin
(kw_xmlelement) @type.builtin
(kw_xmlnamespacemanager) @type.builtin
(kw_xmlnametable) @type.builtin
(kw_xmlnode) @type.builtin
(kw_xmlnodelist) @type.builtin
(kw_xmlport) @type.builtin
(kw_xmlprocessinginstruction) @type.builtin
(kw_xmlreadoptions) @type.builtin
(kw_xmltext) @type.builtin
(kw_xmlwriteoptions) @type.builtin
(kw_action) @keyword.directive
(kw_actions) @keyword.directive
(kw_add) @keyword.directive
(kw_addafter) @keyword.directive
(kw_addbefore) @keyword.directive
(kw_addfirst) @keyword.directive
(kw_addlast) @keyword.directive
(kw_area) @keyword.directive
(kw_assembly) @keyword.directive
(kw_chartpart) @keyword.directive
(kw_column) @keyword.directive
(kw_cuegroup) @keyword.directive
(kw_customizes) @keyword.directive
(kw_dataitem) @keyword.directive
(kw_dataset) @keyword.directive
(kw_elements) @keyword.directive
(kw_extends) @keyword.directive
(kw_field) @keyword.directive
(kw_fieldattribute) @keyword.directive
(kw_fieldelement) @keyword.directive
(kw_fieldgroup) @keyword.directive
(kw_fieldgroups) @keyword.directive
(kw_fields) @keyword.directive
(kw_filter) @keyword.directive
(kw_fixed) @keyword.directive
(kw_grid) @keyword.directive
(kw_group) @keyword.directive
(kw_implements) @keyword.directive
(kw_key) @keyword.directive
(kw_keys) @keyword.directive
(kw_label) @keyword.directive
(kw_labels) @keyword.directive
(kw_layout) @keyword.directive
(kw_modify) @keyword.directive
(kw_moveafter) @keyword.directive
(kw_movebefore) @keyword.directive
(kw_movefirst) @keyword.directive
(kw_movelast) @keyword.directive
(kw_namespace) @keyword.directive
(kw_part) @keyword.directive
(kw_rendering) @keyword.directive
(kw_repeater) @keyword.directive
(kw_requestpage) @keyword.directive
(kw_schema) @keyword.directive
(kw_separator) @keyword.directive
(kw_systempart) @keyword.directive
(kw_tableelement) @keyword.directive
(kw_textattribute) @keyword.directive
(kw_textelement) @keyword.directive
(kw_type) @keyword.directive
(kw_usercontrol) @keyword.directive
(kw_using) @keyword.directive
(kw_value) @keyword.directive
(kw_ascending) @keyword.property
(kw_average) @keyword.property
(kw_const) @keyword.property
(kw_count) @keyword.property
(kw_descending) @keyword.property
(kw_exist) @keyword.property
(kw_field) @keyword.property
(kw_filter) @keyword.property
(kw_lookup) @keyword.property
(kw_max) @keyword.property
(kw_min) @keyword.property
(kw_order) @keyword.property
(kw_sorting) @keyword.property
(kw_sum) @keyword.property
(kw_tabledata) @keyword.property
(kw_upperlimit) @keyword.property
(kw_where) @keyword.property
(kw_and) @keyword.operator
(kw_as) @keyword.operator
(kw_div) @keyword.operator
(kw_is) @keyword.operator
(kw_mod) @keyword.operator
(kw_not) @keyword.operator
(kw_or) @keyword.operator
(kw_xor) @keyword.operator


(operator_word) @keyword.operator
(object_keyword) @keyword.storage.type
(type_keyword) @type.builtin
(metadata_keyword) @keyword.directive
(property_keyword) @keyword.property
(keyword) @keyword.control

; Highlight any name in a property assignment as a property (heuristic for missing TM keywords)
(property_assignment name: (_) @keyword.property)

; --- Punctuation & Operators ---
(operator) @operator
(semicolon) @punctuation.delimiter
(comma) @punctuation.delimiter
["(" ")" "[" "]" "{" "}"] @punctuation.bracket

; --- Names & Calls ---
; Function calls
(call_suffix) @function.call
(member_call_suffix member: (_) @function.call)
(scope_call_suffix member: (_) @function.call)

; Definitions
(procedure_declaration name: (_) @function.method)
(trigger_declaration name: (_) @function.method)
(event_declaration name: (_) @function.method)

(identifier) @variable
