//! Zed language package generation.
//!
//! The extension's `languages/al` directory is generated output. Query files
//! that are canonical tree-sitter outputs are copied from `tree-sitter-al/queries`;
//! Zed-specific config/tasks/runnable metadata live as generator templates here.

use anyhow::{Context, Result, bail};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

/// Query files copied verbatim from `tree-sitter-al/queries`.
///
/// `brackets.scm` and `outline.scm` used to be maintained as separate templates
/// here, which let them drift from the grammar's own copies (the template
/// brackets file was missing the `{`/`}` pair and carried an `@open` with no
/// `@close`). The grammar queries are the single source of truth.
const GENERATED_QUERY_FILES: &[&str] = &[
    "brackets.scm",
    "folds.scm",
    "highlights.scm",
    "indents.scm",
    "locals.scm",
    "outline.scm",
    "textobjects.scm",
];

/// Zed-specific files with no tree-sitter-side equivalent.
///
/// `tasks.json` and `runnables.scm` are a pair: the runnable queries emit the
/// `al-test`, `al-event-publisher` and `al-event-subscriber` tags that the task
/// entries subscribe to, so a tag added to one needs a task in the other or the
/// inline run button resolves to nothing. Both invoke a bare `al-explorer`,
/// which the extension downloads into its work directory but cannot place on
/// PATH — see `Docs/features/language-assets.md` for the install step users
/// need before the tasks resolve.
const TEMPLATE_FILES: &[&str] = &[
    "config.toml",
    "injections.scm",
    "inline_values.scm",
    "overrides.scm",
    "runnables.scm",
    "semantic_token_rules.json",
    "tasks.json",
];

pub fn generate(extension_root: &Path, grammar_queries_dir: &Path) -> Result<()> {
    let language_dir = extension_root.join("languages/al");
    fs::create_dir_all(&language_dir)
        .with_context(|| format!("failed to create {}", language_dir.display()))?;

    for file_name in GENERATED_QUERY_FILES {
        let source = grammar_queries_dir.join(file_name);
        let target = language_dir.join(file_name);
        copy_file(&source, &target)?;
    }

    let template_dir =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tools/al-gen/templates/zed-language");
    for file_name in TEMPLATE_FILES {
        let source = template_dir.join(file_name);
        let target = language_dir.join(file_name);
        copy_file(&source, &target)?;
    }

    ensure_no_unknown_language_files(&language_dir)?;
    println!("Generated {}", language_dir.display());
    Ok(())
}

fn copy_file(source: &Path, target: &Path) -> Result<()> {
    let contents = fs::read_to_string(source)
        .with_context(|| format!("failed to read {}", source.display()))?;
    fs::write(target, contents).with_context(|| format!("failed to write {}", target.display()))
}

fn ensure_no_unknown_language_files(language_dir: &Path) -> Result<()> {
    let expected: BTreeSet<&str> = GENERATED_QUERY_FILES
        .iter()
        .chain(TEMPLATE_FILES.iter())
        .copied()
        .collect();

    for entry in fs::read_dir(language_dir)
        .with_context(|| format!("failed to read {}", language_dir.display()))?
    {
        let entry = entry?;
        let file_type = entry.file_type()?;
        if !file_type.is_file() {
            continue;
        }

        let file_name = entry.file_name();
        let file_name = file_name
            .to_str()
            .with_context(|| format!("non-UTF-8 file name in {}", language_dir.display()))?;
        if !expected.contains(file_name) {
            bail!(
                "{} is not generated by al-gen; add it to the Zed language generator or remove it",
                entry.path().display()
            );
        }
    }

    Ok(())
}
