/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 37
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  sym_integer = 8,
  sym_string = 9,
  sym_verbatim_string = 10,
  sym_quoted_identifier = 11,
  sym_directive = 12,
  sym_comment = 13,
  sym_operator = 14,
  sym_punctuation = 15,
  sym_keyword = 16,
  sym_control_keyword = 17,
  sym_object_keyword = 18,
  sym_type_keyword = 19,
  sym_metadata_keyword = 20,
  sym_property_keyword = 21,
  sym_source_file = 22,
  sym__item = 23,
  sym_object_declaration = 24,
  sym_object_modifier = 25,
  sym__pre_object_body = 26,
  sym_braced_block = 27,
  sym_parenthesized_block = 28,
  sym_bracketed_block = 29,
  sym_name = 30,
  sym__atom = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym_object_declaration_repeat1 = 33,
  aux_sym_braced_block_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_integer] = "integer",
  [sym_string] = "string",
  [sym_verbatim_string] = "verbatim_string",
  [sym_quoted_identifier] = "quoted_identifier",
  [sym_directive] = "directive",
  [sym_comment] = "comment",
  [sym_operator] = "operator",
  [sym_punctuation] = "punctuation",
  [sym_keyword] = "keyword",
  [sym_control_keyword] = "control_keyword",
  [sym_object_keyword] = "object_keyword",
  [sym_type_keyword] = "type_keyword",
  [sym_metadata_keyword] = "metadata_keyword",
  [sym_property_keyword] = "property_keyword",
  [sym_source_file] = "source_file",
  [sym__item] = "_item",
  [sym_object_declaration] = "object_declaration",
  [sym_object_modifier] = "object_modifier",
  [sym__pre_object_body] = "_pre_object_body",
  [sym_braced_block] = "braced_block",
  [sym_parenthesized_block] = "parenthesized_block",
  [sym_bracketed_block] = "bracketed_block",
  [sym_name] = "name",
  [sym__atom] = "_atom",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_object_declaration_repeat1] = "object_declaration_repeat1",
  [aux_sym_braced_block_repeat1] = "braced_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_integer] = sym_integer,
  [sym_string] = sym_string,
  [sym_verbatim_string] = sym_verbatim_string,
  [sym_quoted_identifier] = sym_quoted_identifier,
  [sym_directive] = sym_directive,
  [sym_comment] = sym_comment,
  [sym_operator] = sym_operator,
  [sym_punctuation] = sym_punctuation,
  [sym_keyword] = sym_keyword,
  [sym_control_keyword] = sym_control_keyword,
  [sym_object_keyword] = sym_object_keyword,
  [sym_type_keyword] = sym_type_keyword,
  [sym_metadata_keyword] = sym_metadata_keyword,
  [sym_property_keyword] = sym_property_keyword,
  [sym_source_file] = sym_source_file,
  [sym__item] = sym__item,
  [sym_object_declaration] = sym_object_declaration,
  [sym_object_modifier] = sym_object_modifier,
  [sym__pre_object_body] = sym__pre_object_body,
  [sym_braced_block] = sym_braced_block,
  [sym_parenthesized_block] = sym_parenthesized_block,
  [sym_bracketed_block] = sym_bracketed_block,
  [sym_name] = sym_name,
  [sym__atom] = sym__atom,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_object_declaration_repeat1] = aux_sym_object_declaration_repeat1,
  [aux_sym_braced_block_repeat1] = aux_sym_braced_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_verbatim_string] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_control_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_object_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_type_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_metadata_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_property_keyword] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__item] = {
    .visible = false,
    .named = true,
  },
  [sym_object_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_object_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym__pre_object_body] = {
    .visible = false,
    .named = true,
  },
  [sym_braced_block] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_block] = {
    .visible = true,
    .named = true,
  },
  [sym_bracketed_block] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_object_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_braced_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_id = 2,
  field_kind = 3,
  field_modifier = 4,
  field_name = 5,
  field_target = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_id] = "id",
  [field_kind] = "kind",
  [field_modifier] = "modifier",
  [field_name] = "name",
  [field_target] = "target",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 4},
  [3] = {.index = 7, .length = 2},
  [4] = {.index = 9, .length = 3},
  [5] = {.index = 12, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 2},
    {field_kind, 0},
    {field_name, 1},
  [3] =
    {field_body, 3},
    {field_id, 1},
    {field_kind, 0},
    {field_name, 2},
  [7] =
    {field_modifier, 0},
    {field_target, 1},
  [9] =
    {field_body, 3},
    {field_kind, 0},
    {field_name, 1},
  [12] =
    {field_body, 4},
    {field_id, 1},
    {field_kind, 0},
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 7,
  [14] = 14,
  [15] = 15,
  [16] = 6,
  [17] = 5,
  [18] = 11,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 21,
  [32] = 32,
  [33] = 20,
  [34] = 24,
  [35] = 23,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static const TSCharacterRange sym_operator_character_set_1[] = {
  {'!', '!'}, {'$', '&'}, {'*', '+'}, {'-', '/'}, {':', ':'}, {'<', '@'}, {'^', '^'}, {'|', '|'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '"', 1,
        '#', 20,
        '\'', 2,
        '(', 11,
        ')', 12,
        '/', 26,
        '@', 25,
        '[', 13,
        ']', 14,
        '{', 9,
        '}', 10,
        ',', 30,
        ';', 30,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('!' <= lookahead && lookahead <= '?') ||
          lookahead == '^' ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(29);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(19);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(18);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(21);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (eof) ADVANCE(8);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '/') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(15);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0x80 <= lookahead && lookahead <= 0xffff)) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '\'') ADVANCE(2);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_verbatim_string);
      if (lookahead == '\'') ADVANCE(3);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_quoted_identifier);
      if (lookahead == '"') ADVANCE(1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_directive);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_comment);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(29);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '\'') ADVANCE(3);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '*') ADVANCE(28);
      if (lookahead == '/') ADVANCE(23);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '*') ADVANCE(27);
      if (lookahead == '/') ADVANCE(22);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(28);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '*') ADVANCE(27);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(28);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_operator);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_punctuation);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 1},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 0, .external_lex_state = 1},
  [6] = {.lex_state = 0, .external_lex_state = 1},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 0, .external_lex_state = 1},
  [10] = {.lex_state = 0, .external_lex_state = 1},
  [11] = {.lex_state = 0, .external_lex_state = 1},
  [12] = {.lex_state = 0, .external_lex_state = 1},
  [13] = {.lex_state = 0, .external_lex_state = 1},
  [14] = {.lex_state = 0, .external_lex_state = 1},
  [15] = {.lex_state = 0, .external_lex_state = 1},
  [16] = {.lex_state = 0, .external_lex_state = 1},
  [17] = {.lex_state = 0, .external_lex_state = 1},
  [18] = {.lex_state = 0, .external_lex_state = 1},
  [19] = {.lex_state = 0, .external_lex_state = 1},
  [20] = {.lex_state = 0, .external_lex_state = 1},
  [21] = {.lex_state = 0, .external_lex_state = 1},
  [22] = {.lex_state = 0, .external_lex_state = 1},
  [23] = {.lex_state = 0, .external_lex_state = 1},
  [24] = {.lex_state = 0, .external_lex_state = 1},
  [25] = {.lex_state = 0, .external_lex_state = 1},
  [26] = {.lex_state = 0, .external_lex_state = 1},
  [27] = {.lex_state = 0, .external_lex_state = 1},
  [28] = {.lex_state = 0, .external_lex_state = 1},
  [29] = {.lex_state = 0, .external_lex_state = 1},
  [30] = {.lex_state = 0, .external_lex_state = 1},
  [31] = {.lex_state = 0, .external_lex_state = 1},
  [32] = {.lex_state = 0, .external_lex_state = 1},
  [33] = {.lex_state = 0, .external_lex_state = 1},
  [34] = {.lex_state = 0, .external_lex_state = 1},
  [35] = {.lex_state = 0, .external_lex_state = 1},
  [36] = {.lex_state = 0, .external_lex_state = 1},
  [37] = {.lex_state = 7},
  [38] = {.lex_state = 7},
  [39] = {.lex_state = 7},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_verbatim_string] = ACTIONS(1),
    [sym_quoted_identifier] = ACTIONS(1),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(1),
    [sym_punctuation] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [sym_control_keyword] = ACTIONS(1),
    [sym_object_keyword] = ACTIONS(1),
    [sym_type_keyword] = ACTIONS(1),
    [sym_metadata_keyword] = ACTIONS(1),
    [sym_property_keyword] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym__item] = STATE(2),
    [sym_object_declaration] = STATE(2),
    [sym_braced_block] = STATE(2),
    [sym_parenthesized_block] = STATE(2),
    [sym_bracketed_block] = STATE(2),
    [sym__atom] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_integer] = ACTIONS(9),
    [sym_string] = ACTIONS(9),
    [sym_verbatim_string] = ACTIONS(9),
    [sym_quoted_identifier] = ACTIONS(9),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(17),
    [sym_punctuation] = ACTIONS(9),
    [sym_keyword] = ACTIONS(9),
    [sym_control_keyword] = ACTIONS(9),
    [sym_object_keyword] = ACTIONS(19),
    [sym_type_keyword] = ACTIONS(9),
    [sym_metadata_keyword] = ACTIONS(9),
    [sym_property_keyword] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym__item] = STATE(3),
    [sym_object_declaration] = STATE(3),
    [sym_braced_block] = STATE(3),
    [sym_parenthesized_block] = STATE(3),
    [sym_bracketed_block] = STATE(3),
    [sym__atom] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_identifier] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_integer] = ACTIONS(23),
    [sym_string] = ACTIONS(23),
    [sym_verbatim_string] = ACTIONS(23),
    [sym_quoted_identifier] = ACTIONS(23),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(25),
    [sym_punctuation] = ACTIONS(23),
    [sym_keyword] = ACTIONS(23),
    [sym_control_keyword] = ACTIONS(23),
    [sym_object_keyword] = ACTIONS(19),
    [sym_type_keyword] = ACTIONS(23),
    [sym_metadata_keyword] = ACTIONS(23),
    [sym_property_keyword] = ACTIONS(23),
  },
  [STATE(3)] = {
    [sym__item] = STATE(3),
    [sym_object_declaration] = STATE(3),
    [sym_braced_block] = STATE(3),
    [sym_parenthesized_block] = STATE(3),
    [sym_bracketed_block] = STATE(3),
    [sym__atom] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_identifier] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(32),
    [anon_sym_LPAREN] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(38),
    [sym_integer] = ACTIONS(29),
    [sym_string] = ACTIONS(29),
    [sym_verbatim_string] = ACTIONS(29),
    [sym_quoted_identifier] = ACTIONS(29),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(41),
    [sym_punctuation] = ACTIONS(29),
    [sym_keyword] = ACTIONS(29),
    [sym_control_keyword] = ACTIONS(29),
    [sym_object_keyword] = ACTIONS(44),
    [sym_type_keyword] = ACTIONS(29),
    [sym_metadata_keyword] = ACTIONS(29),
    [sym_property_keyword] = ACTIONS(29),
  },
  [STATE(4)] = {
    [sym_braced_block] = STATE(4),
    [sym_parenthesized_block] = STATE(4),
    [sym_bracketed_block] = STATE(4),
    [sym__atom] = STATE(4),
    [aux_sym_braced_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(47),
    [anon_sym_LBRACE] = ACTIONS(50),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(55),
    [anon_sym_RPAREN] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(58),
    [anon_sym_RBRACK] = ACTIONS(53),
    [sym_integer] = ACTIONS(47),
    [sym_string] = ACTIONS(47),
    [sym_verbatim_string] = ACTIONS(47),
    [sym_quoted_identifier] = ACTIONS(47),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(61),
    [sym_punctuation] = ACTIONS(47),
    [sym_keyword] = ACTIONS(47),
    [sym_control_keyword] = ACTIONS(47),
    [sym_object_keyword] = ACTIONS(47),
    [sym_type_keyword] = ACTIONS(47),
    [sym_metadata_keyword] = ACTIONS(47),
    [sym_property_keyword] = ACTIONS(47),
  },
  [STATE(5)] = {
    [sym_braced_block] = STATE(4),
    [sym_parenthesized_block] = STATE(4),
    [sym_bracketed_block] = STATE(4),
    [sym__atom] = STATE(4),
    [aux_sym_braced_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(66),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_integer] = ACTIONS(64),
    [sym_string] = ACTIONS(64),
    [sym_verbatim_string] = ACTIONS(64),
    [sym_quoted_identifier] = ACTIONS(64),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(68),
    [sym_punctuation] = ACTIONS(64),
    [sym_keyword] = ACTIONS(64),
    [sym_control_keyword] = ACTIONS(64),
    [sym_object_keyword] = ACTIONS(64),
    [sym_type_keyword] = ACTIONS(64),
    [sym_metadata_keyword] = ACTIONS(64),
    [sym_property_keyword] = ACTIONS(64),
  },
  [STATE(6)] = {
    [sym_braced_block] = STATE(5),
    [sym_parenthesized_block] = STATE(5),
    [sym_bracketed_block] = STATE(5),
    [sym__atom] = STATE(5),
    [aux_sym_braced_block_repeat1] = STATE(5),
    [sym_identifier] = ACTIONS(70),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(72),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_integer] = ACTIONS(70),
    [sym_string] = ACTIONS(70),
    [sym_verbatim_string] = ACTIONS(70),
    [sym_quoted_identifier] = ACTIONS(70),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(74),
    [sym_punctuation] = ACTIONS(70),
    [sym_keyword] = ACTIONS(70),
    [sym_control_keyword] = ACTIONS(70),
    [sym_object_keyword] = ACTIONS(70),
    [sym_type_keyword] = ACTIONS(70),
    [sym_metadata_keyword] = ACTIONS(70),
    [sym_property_keyword] = ACTIONS(70),
  },
  [STATE(7)] = {
    [sym_braced_block] = STATE(11),
    [sym_parenthesized_block] = STATE(11),
    [sym_bracketed_block] = STATE(11),
    [sym__atom] = STATE(11),
    [aux_sym_braced_block_repeat1] = STATE(11),
    [sym_identifier] = ACTIONS(76),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(78),
    [sym_integer] = ACTIONS(76),
    [sym_string] = ACTIONS(76),
    [sym_verbatim_string] = ACTIONS(76),
    [sym_quoted_identifier] = ACTIONS(76),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(80),
    [sym_punctuation] = ACTIONS(76),
    [sym_keyword] = ACTIONS(76),
    [sym_control_keyword] = ACTIONS(76),
    [sym_object_keyword] = ACTIONS(76),
    [sym_type_keyword] = ACTIONS(76),
    [sym_metadata_keyword] = ACTIONS(76),
    [sym_property_keyword] = ACTIONS(76),
  },
  [STATE(8)] = {
    [sym_braced_block] = STATE(10),
    [sym_parenthesized_block] = STATE(10),
    [sym_bracketed_block] = STATE(10),
    [sym__atom] = STATE(10),
    [aux_sym_braced_block_repeat1] = STATE(10),
    [sym_identifier] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(84),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_integer] = ACTIONS(82),
    [sym_string] = ACTIONS(82),
    [sym_verbatim_string] = ACTIONS(82),
    [sym_quoted_identifier] = ACTIONS(82),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(86),
    [sym_punctuation] = ACTIONS(82),
    [sym_keyword] = ACTIONS(82),
    [sym_control_keyword] = ACTIONS(82),
    [sym_object_keyword] = ACTIONS(82),
    [sym_type_keyword] = ACTIONS(82),
    [sym_metadata_keyword] = ACTIONS(82),
    [sym_property_keyword] = ACTIONS(82),
  },
  [STATE(9)] = {
    [sym_object_modifier] = STATE(12),
    [sym__pre_object_body] = STATE(12),
    [sym_braced_block] = STATE(27),
    [sym_parenthesized_block] = STATE(12),
    [sym_bracketed_block] = STATE(12),
    [aux_sym_object_declaration_repeat1] = STATE(12),
    [sym_identifier] = ACTIONS(88),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(92),
    [sym_integer] = ACTIONS(88),
    [sym_string] = ACTIONS(88),
    [sym_verbatim_string] = ACTIONS(88),
    [sym_quoted_identifier] = ACTIONS(88),
    [sym_directive] = ACTIONS(88),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(94),
    [sym_punctuation] = ACTIONS(88),
    [sym_keyword] = ACTIONS(88),
    [sym_control_keyword] = ACTIONS(88),
    [sym_object_keyword] = ACTIONS(88),
    [sym_type_keyword] = ACTIONS(88),
    [sym_metadata_keyword] = ACTIONS(96),
    [sym_property_keyword] = ACTIONS(88),
  },
  [STATE(10)] = {
    [sym_braced_block] = STATE(4),
    [sym_parenthesized_block] = STATE(4),
    [sym_bracketed_block] = STATE(4),
    [sym__atom] = STATE(4),
    [aux_sym_braced_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_RBRACE] = ACTIONS(98),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_integer] = ACTIONS(64),
    [sym_string] = ACTIONS(64),
    [sym_verbatim_string] = ACTIONS(64),
    [sym_quoted_identifier] = ACTIONS(64),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(68),
    [sym_punctuation] = ACTIONS(64),
    [sym_keyword] = ACTIONS(64),
    [sym_control_keyword] = ACTIONS(64),
    [sym_object_keyword] = ACTIONS(64),
    [sym_type_keyword] = ACTIONS(64),
    [sym_metadata_keyword] = ACTIONS(64),
    [sym_property_keyword] = ACTIONS(64),
  },
  [STATE(11)] = {
    [sym_braced_block] = STATE(4),
    [sym_parenthesized_block] = STATE(4),
    [sym_bracketed_block] = STATE(4),
    [sym__atom] = STATE(4),
    [aux_sym_braced_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(100),
    [sym_integer] = ACTIONS(64),
    [sym_string] = ACTIONS(64),
    [sym_verbatim_string] = ACTIONS(64),
    [sym_quoted_identifier] = ACTIONS(64),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(68),
    [sym_punctuation] = ACTIONS(64),
    [sym_keyword] = ACTIONS(64),
    [sym_control_keyword] = ACTIONS(64),
    [sym_object_keyword] = ACTIONS(64),
    [sym_type_keyword] = ACTIONS(64),
    [sym_metadata_keyword] = ACTIONS(64),
    [sym_property_keyword] = ACTIONS(64),
  },
  [STATE(12)] = {
    [sym_object_modifier] = STATE(19),
    [sym__pre_object_body] = STATE(19),
    [sym_braced_block] = STATE(29),
    [sym_parenthesized_block] = STATE(19),
    [sym_bracketed_block] = STATE(19),
    [aux_sym_object_declaration_repeat1] = STATE(19),
    [sym_identifier] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(92),
    [sym_integer] = ACTIONS(102),
    [sym_string] = ACTIONS(102),
    [sym_verbatim_string] = ACTIONS(102),
    [sym_quoted_identifier] = ACTIONS(102),
    [sym_directive] = ACTIONS(102),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(104),
    [sym_punctuation] = ACTIONS(102),
    [sym_keyword] = ACTIONS(102),
    [sym_control_keyword] = ACTIONS(102),
    [sym_object_keyword] = ACTIONS(102),
    [sym_type_keyword] = ACTIONS(102),
    [sym_metadata_keyword] = ACTIONS(96),
    [sym_property_keyword] = ACTIONS(102),
  },
  [STATE(13)] = {
    [sym_braced_block] = STATE(18),
    [sym_parenthesized_block] = STATE(18),
    [sym_bracketed_block] = STATE(18),
    [sym__atom] = STATE(18),
    [aux_sym_braced_block_repeat1] = STATE(18),
    [sym_identifier] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(108),
    [sym_integer] = ACTIONS(106),
    [sym_string] = ACTIONS(106),
    [sym_verbatim_string] = ACTIONS(106),
    [sym_quoted_identifier] = ACTIONS(106),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(110),
    [sym_punctuation] = ACTIONS(106),
    [sym_keyword] = ACTIONS(106),
    [sym_control_keyword] = ACTIONS(106),
    [sym_object_keyword] = ACTIONS(106),
    [sym_type_keyword] = ACTIONS(106),
    [sym_metadata_keyword] = ACTIONS(106),
    [sym_property_keyword] = ACTIONS(106),
  },
  [STATE(14)] = {
    [sym_object_modifier] = STATE(15),
    [sym__pre_object_body] = STATE(15),
    [sym_braced_block] = STATE(30),
    [sym_parenthesized_block] = STATE(15),
    [sym_bracketed_block] = STATE(15),
    [aux_sym_object_declaration_repeat1] = STATE(15),
    [sym_identifier] = ACTIONS(112),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(92),
    [sym_integer] = ACTIONS(112),
    [sym_string] = ACTIONS(112),
    [sym_verbatim_string] = ACTIONS(112),
    [sym_quoted_identifier] = ACTIONS(112),
    [sym_directive] = ACTIONS(112),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(114),
    [sym_punctuation] = ACTIONS(112),
    [sym_keyword] = ACTIONS(112),
    [sym_control_keyword] = ACTIONS(112),
    [sym_object_keyword] = ACTIONS(112),
    [sym_type_keyword] = ACTIONS(112),
    [sym_metadata_keyword] = ACTIONS(96),
    [sym_property_keyword] = ACTIONS(112),
  },
  [STATE(15)] = {
    [sym_object_modifier] = STATE(19),
    [sym__pre_object_body] = STATE(19),
    [sym_braced_block] = STATE(28),
    [sym_parenthesized_block] = STATE(19),
    [sym_bracketed_block] = STATE(19),
    [aux_sym_object_declaration_repeat1] = STATE(19),
    [sym_identifier] = ACTIONS(102),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(90),
    [anon_sym_LBRACK] = ACTIONS(92),
    [sym_integer] = ACTIONS(102),
    [sym_string] = ACTIONS(102),
    [sym_verbatim_string] = ACTIONS(102),
    [sym_quoted_identifier] = ACTIONS(102),
    [sym_directive] = ACTIONS(102),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(104),
    [sym_punctuation] = ACTIONS(102),
    [sym_keyword] = ACTIONS(102),
    [sym_control_keyword] = ACTIONS(102),
    [sym_object_keyword] = ACTIONS(102),
    [sym_type_keyword] = ACTIONS(102),
    [sym_metadata_keyword] = ACTIONS(96),
    [sym_property_keyword] = ACTIONS(102),
  },
  [STATE(16)] = {
    [sym_braced_block] = STATE(17),
    [sym_parenthesized_block] = STATE(17),
    [sym_bracketed_block] = STATE(17),
    [sym__atom] = STATE(17),
    [aux_sym_braced_block_repeat1] = STATE(17),
    [sym_identifier] = ACTIONS(116),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(118),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_integer] = ACTIONS(116),
    [sym_string] = ACTIONS(116),
    [sym_verbatim_string] = ACTIONS(116),
    [sym_quoted_identifier] = ACTIONS(116),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(120),
    [sym_punctuation] = ACTIONS(116),
    [sym_keyword] = ACTIONS(116),
    [sym_control_keyword] = ACTIONS(116),
    [sym_object_keyword] = ACTIONS(116),
    [sym_type_keyword] = ACTIONS(116),
    [sym_metadata_keyword] = ACTIONS(116),
    [sym_property_keyword] = ACTIONS(116),
  },
  [STATE(17)] = {
    [sym_braced_block] = STATE(4),
    [sym_parenthesized_block] = STATE(4),
    [sym_bracketed_block] = STATE(4),
    [sym__atom] = STATE(4),
    [aux_sym_braced_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_RPAREN] = ACTIONS(122),
    [anon_sym_LBRACK] = ACTIONS(15),
    [sym_integer] = ACTIONS(64),
    [sym_string] = ACTIONS(64),
    [sym_verbatim_string] = ACTIONS(64),
    [sym_quoted_identifier] = ACTIONS(64),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(68),
    [sym_punctuation] = ACTIONS(64),
    [sym_keyword] = ACTIONS(64),
    [sym_control_keyword] = ACTIONS(64),
    [sym_object_keyword] = ACTIONS(64),
    [sym_type_keyword] = ACTIONS(64),
    [sym_metadata_keyword] = ACTIONS(64),
    [sym_property_keyword] = ACTIONS(64),
  },
  [STATE(18)] = {
    [sym_braced_block] = STATE(4),
    [sym_parenthesized_block] = STATE(4),
    [sym_bracketed_block] = STATE(4),
    [sym__atom] = STATE(4),
    [aux_sym_braced_block_repeat1] = STATE(4),
    [sym_identifier] = ACTIONS(64),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LPAREN] = ACTIONS(13),
    [anon_sym_LBRACK] = ACTIONS(15),
    [anon_sym_RBRACK] = ACTIONS(124),
    [sym_integer] = ACTIONS(64),
    [sym_string] = ACTIONS(64),
    [sym_verbatim_string] = ACTIONS(64),
    [sym_quoted_identifier] = ACTIONS(64),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(68),
    [sym_punctuation] = ACTIONS(64),
    [sym_keyword] = ACTIONS(64),
    [sym_control_keyword] = ACTIONS(64),
    [sym_object_keyword] = ACTIONS(64),
    [sym_type_keyword] = ACTIONS(64),
    [sym_metadata_keyword] = ACTIONS(64),
    [sym_property_keyword] = ACTIONS(64),
  },
  [STATE(19)] = {
    [sym_object_modifier] = STATE(19),
    [sym__pre_object_body] = STATE(19),
    [sym_parenthesized_block] = STATE(19),
    [sym_bracketed_block] = STATE(19),
    [aux_sym_object_declaration_repeat1] = STATE(19),
    [sym_identifier] = ACTIONS(126),
    [anon_sym_LBRACE] = ACTIONS(129),
    [anon_sym_LPAREN] = ACTIONS(131),
    [anon_sym_LBRACK] = ACTIONS(134),
    [sym_integer] = ACTIONS(126),
    [sym_string] = ACTIONS(126),
    [sym_verbatim_string] = ACTIONS(126),
    [sym_quoted_identifier] = ACTIONS(126),
    [sym_directive] = ACTIONS(126),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(137),
    [sym_punctuation] = ACTIONS(126),
    [sym_keyword] = ACTIONS(126),
    [sym_control_keyword] = ACTIONS(126),
    [sym_object_keyword] = ACTIONS(126),
    [sym_type_keyword] = ACTIONS(126),
    [sym_metadata_keyword] = ACTIONS(140),
    [sym_property_keyword] = ACTIONS(126),
  },
  [STATE(20)] = {
    [ts_builtin_sym_end] = ACTIONS(143),
    [sym_identifier] = ACTIONS(143),
    [anon_sym_LBRACE] = ACTIONS(143),
    [anon_sym_RBRACE] = ACTIONS(143),
    [anon_sym_LPAREN] = ACTIONS(143),
    [anon_sym_RPAREN] = ACTIONS(143),
    [anon_sym_LBRACK] = ACTIONS(143),
    [anon_sym_RBRACK] = ACTIONS(143),
    [sym_integer] = ACTIONS(143),
    [sym_string] = ACTIONS(143),
    [sym_verbatim_string] = ACTIONS(143),
    [sym_quoted_identifier] = ACTIONS(143),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(145),
    [sym_punctuation] = ACTIONS(143),
    [sym_keyword] = ACTIONS(143),
    [sym_control_keyword] = ACTIONS(143),
    [sym_object_keyword] = ACTIONS(143),
    [sym_type_keyword] = ACTIONS(143),
    [sym_metadata_keyword] = ACTIONS(143),
    [sym_property_keyword] = ACTIONS(143),
  },
  [STATE(21)] = {
    [ts_builtin_sym_end] = ACTIONS(147),
    [sym_identifier] = ACTIONS(147),
    [anon_sym_LBRACE] = ACTIONS(147),
    [anon_sym_RBRACE] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(147),
    [anon_sym_RPAREN] = ACTIONS(147),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(147),
    [sym_integer] = ACTIONS(147),
    [sym_string] = ACTIONS(147),
    [sym_verbatim_string] = ACTIONS(147),
    [sym_quoted_identifier] = ACTIONS(147),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(149),
    [sym_punctuation] = ACTIONS(147),
    [sym_keyword] = ACTIONS(147),
    [sym_control_keyword] = ACTIONS(147),
    [sym_object_keyword] = ACTIONS(147),
    [sym_type_keyword] = ACTIONS(147),
    [sym_metadata_keyword] = ACTIONS(147),
    [sym_property_keyword] = ACTIONS(147),
  },
  [STATE(22)] = {
    [ts_builtin_sym_end] = ACTIONS(151),
    [sym_identifier] = ACTIONS(151),
    [anon_sym_LBRACE] = ACTIONS(151),
    [anon_sym_RBRACE] = ACTIONS(151),
    [anon_sym_LPAREN] = ACTIONS(151),
    [anon_sym_RPAREN] = ACTIONS(151),
    [anon_sym_LBRACK] = ACTIONS(151),
    [anon_sym_RBRACK] = ACTIONS(151),
    [sym_integer] = ACTIONS(151),
    [sym_string] = ACTIONS(151),
    [sym_verbatim_string] = ACTIONS(151),
    [sym_quoted_identifier] = ACTIONS(151),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(153),
    [sym_punctuation] = ACTIONS(151),
    [sym_keyword] = ACTIONS(151),
    [sym_control_keyword] = ACTIONS(151),
    [sym_object_keyword] = ACTIONS(151),
    [sym_type_keyword] = ACTIONS(151),
    [sym_metadata_keyword] = ACTIONS(151),
    [sym_property_keyword] = ACTIONS(151),
  },
  [STATE(23)] = {
    [ts_builtin_sym_end] = ACTIONS(155),
    [sym_identifier] = ACTIONS(155),
    [anon_sym_LBRACE] = ACTIONS(155),
    [anon_sym_RBRACE] = ACTIONS(155),
    [anon_sym_LPAREN] = ACTIONS(155),
    [anon_sym_RPAREN] = ACTIONS(155),
    [anon_sym_LBRACK] = ACTIONS(155),
    [anon_sym_RBRACK] = ACTIONS(155),
    [sym_integer] = ACTIONS(155),
    [sym_string] = ACTIONS(155),
    [sym_verbatim_string] = ACTIONS(155),
    [sym_quoted_identifier] = ACTIONS(155),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(157),
    [sym_punctuation] = ACTIONS(155),
    [sym_keyword] = ACTIONS(155),
    [sym_control_keyword] = ACTIONS(155),
    [sym_object_keyword] = ACTIONS(155),
    [sym_type_keyword] = ACTIONS(155),
    [sym_metadata_keyword] = ACTIONS(155),
    [sym_property_keyword] = ACTIONS(155),
  },
  [STATE(24)] = {
    [ts_builtin_sym_end] = ACTIONS(159),
    [sym_identifier] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(159),
    [anon_sym_RBRACE] = ACTIONS(159),
    [anon_sym_LPAREN] = ACTIONS(159),
    [anon_sym_RPAREN] = ACTIONS(159),
    [anon_sym_LBRACK] = ACTIONS(159),
    [anon_sym_RBRACK] = ACTIONS(159),
    [sym_integer] = ACTIONS(159),
    [sym_string] = ACTIONS(159),
    [sym_verbatim_string] = ACTIONS(159),
    [sym_quoted_identifier] = ACTIONS(159),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(161),
    [sym_punctuation] = ACTIONS(159),
    [sym_keyword] = ACTIONS(159),
    [sym_control_keyword] = ACTIONS(159),
    [sym_object_keyword] = ACTIONS(159),
    [sym_type_keyword] = ACTIONS(159),
    [sym_metadata_keyword] = ACTIONS(159),
    [sym_property_keyword] = ACTIONS(159),
  },
  [STATE(25)] = {
    [ts_builtin_sym_end] = ACTIONS(163),
    [sym_identifier] = ACTIONS(163),
    [anon_sym_LBRACE] = ACTIONS(163),
    [anon_sym_RBRACE] = ACTIONS(163),
    [anon_sym_LPAREN] = ACTIONS(163),
    [anon_sym_RPAREN] = ACTIONS(163),
    [anon_sym_LBRACK] = ACTIONS(163),
    [anon_sym_RBRACK] = ACTIONS(163),
    [sym_integer] = ACTIONS(163),
    [sym_string] = ACTIONS(163),
    [sym_verbatim_string] = ACTIONS(163),
    [sym_quoted_identifier] = ACTIONS(163),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(165),
    [sym_punctuation] = ACTIONS(163),
    [sym_keyword] = ACTIONS(163),
    [sym_control_keyword] = ACTIONS(163),
    [sym_object_keyword] = ACTIONS(163),
    [sym_type_keyword] = ACTIONS(163),
    [sym_metadata_keyword] = ACTIONS(163),
    [sym_property_keyword] = ACTIONS(163),
  },
  [STATE(26)] = {
    [sym_name] = STATE(9),
    [ts_builtin_sym_end] = ACTIONS(167),
    [sym_identifier] = ACTIONS(169),
    [anon_sym_LBRACE] = ACTIONS(167),
    [anon_sym_LPAREN] = ACTIONS(167),
    [anon_sym_LBRACK] = ACTIONS(167),
    [sym_integer] = ACTIONS(171),
    [sym_string] = ACTIONS(167),
    [sym_verbatim_string] = ACTIONS(167),
    [sym_quoted_identifier] = ACTIONS(169),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(173),
    [sym_punctuation] = ACTIONS(167),
    [sym_keyword] = ACTIONS(167),
    [sym_control_keyword] = ACTIONS(167),
    [sym_object_keyword] = ACTIONS(167),
    [sym_type_keyword] = ACTIONS(167),
    [sym_metadata_keyword] = ACTIONS(167),
    [sym_property_keyword] = ACTIONS(167),
  },
  [STATE(27)] = {
    [ts_builtin_sym_end] = ACTIONS(175),
    [sym_identifier] = ACTIONS(175),
    [anon_sym_LBRACE] = ACTIONS(175),
    [anon_sym_LPAREN] = ACTIONS(175),
    [anon_sym_LBRACK] = ACTIONS(175),
    [sym_integer] = ACTIONS(175),
    [sym_string] = ACTIONS(175),
    [sym_verbatim_string] = ACTIONS(175),
    [sym_quoted_identifier] = ACTIONS(175),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(177),
    [sym_punctuation] = ACTIONS(175),
    [sym_keyword] = ACTIONS(175),
    [sym_control_keyword] = ACTIONS(175),
    [sym_object_keyword] = ACTIONS(175),
    [sym_type_keyword] = ACTIONS(175),
    [sym_metadata_keyword] = ACTIONS(175),
    [sym_property_keyword] = ACTIONS(175),
  },
  [STATE(28)] = {
    [ts_builtin_sym_end] = ACTIONS(179),
    [sym_identifier] = ACTIONS(179),
    [anon_sym_LBRACE] = ACTIONS(179),
    [anon_sym_LPAREN] = ACTIONS(179),
    [anon_sym_LBRACK] = ACTIONS(179),
    [sym_integer] = ACTIONS(179),
    [sym_string] = ACTIONS(179),
    [sym_verbatim_string] = ACTIONS(179),
    [sym_quoted_identifier] = ACTIONS(179),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(181),
    [sym_punctuation] = ACTIONS(179),
    [sym_keyword] = ACTIONS(179),
    [sym_control_keyword] = ACTIONS(179),
    [sym_object_keyword] = ACTIONS(179),
    [sym_type_keyword] = ACTIONS(179),
    [sym_metadata_keyword] = ACTIONS(179),
    [sym_property_keyword] = ACTIONS(179),
  },
  [STATE(29)] = {
    [ts_builtin_sym_end] = ACTIONS(183),
    [sym_identifier] = ACTIONS(183),
    [anon_sym_LBRACE] = ACTIONS(183),
    [anon_sym_LPAREN] = ACTIONS(183),
    [anon_sym_LBRACK] = ACTIONS(183),
    [sym_integer] = ACTIONS(183),
    [sym_string] = ACTIONS(183),
    [sym_verbatim_string] = ACTIONS(183),
    [sym_quoted_identifier] = ACTIONS(183),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(185),
    [sym_punctuation] = ACTIONS(183),
    [sym_keyword] = ACTIONS(183),
    [sym_control_keyword] = ACTIONS(183),
    [sym_object_keyword] = ACTIONS(183),
    [sym_type_keyword] = ACTIONS(183),
    [sym_metadata_keyword] = ACTIONS(183),
    [sym_property_keyword] = ACTIONS(183),
  },
  [STATE(30)] = {
    [ts_builtin_sym_end] = ACTIONS(187),
    [sym_identifier] = ACTIONS(187),
    [anon_sym_LBRACE] = ACTIONS(187),
    [anon_sym_LPAREN] = ACTIONS(187),
    [anon_sym_LBRACK] = ACTIONS(187),
    [sym_integer] = ACTIONS(187),
    [sym_string] = ACTIONS(187),
    [sym_verbatim_string] = ACTIONS(187),
    [sym_quoted_identifier] = ACTIONS(187),
    [sym_directive] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(189),
    [sym_punctuation] = ACTIONS(187),
    [sym_keyword] = ACTIONS(187),
    [sym_control_keyword] = ACTIONS(187),
    [sym_object_keyword] = ACTIONS(187),
    [sym_type_keyword] = ACTIONS(187),
    [sym_metadata_keyword] = ACTIONS(187),
    [sym_property_keyword] = ACTIONS(187),
  },
  [STATE(31)] = {
    [sym_identifier] = ACTIONS(147),
    [anon_sym_LBRACE] = ACTIONS(147),
    [anon_sym_LPAREN] = ACTIONS(147),
    [anon_sym_LBRACK] = ACTIONS(147),
    [sym_integer] = ACTIONS(147),
    [sym_string] = ACTIONS(147),
    [sym_verbatim_string] = ACTIONS(147),
    [sym_quoted_identifier] = ACTIONS(147),
    [sym_directive] = ACTIONS(147),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(149),
    [sym_punctuation] = ACTIONS(147),
    [sym_keyword] = ACTIONS(147),
    [sym_control_keyword] = ACTIONS(147),
    [sym_object_keyword] = ACTIONS(147),
    [sym_type_keyword] = ACTIONS(147),
    [sym_metadata_keyword] = ACTIONS(147),
    [sym_property_keyword] = ACTIONS(147),
  },
  [STATE(32)] = {
    [sym_identifier] = ACTIONS(191),
    [anon_sym_LBRACE] = ACTIONS(191),
    [anon_sym_LPAREN] = ACTIONS(191),
    [anon_sym_LBRACK] = ACTIONS(191),
    [sym_integer] = ACTIONS(191),
    [sym_string] = ACTIONS(191),
    [sym_verbatim_string] = ACTIONS(191),
    [sym_quoted_identifier] = ACTIONS(191),
    [sym_directive] = ACTIONS(191),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(193),
    [sym_punctuation] = ACTIONS(191),
    [sym_keyword] = ACTIONS(191),
    [sym_control_keyword] = ACTIONS(191),
    [sym_object_keyword] = ACTIONS(191),
    [sym_type_keyword] = ACTIONS(191),
    [sym_metadata_keyword] = ACTIONS(191),
    [sym_property_keyword] = ACTIONS(191),
  },
  [STATE(33)] = {
    [sym_identifier] = ACTIONS(143),
    [anon_sym_LBRACE] = ACTIONS(143),
    [anon_sym_LPAREN] = ACTIONS(143),
    [anon_sym_LBRACK] = ACTIONS(143),
    [sym_integer] = ACTIONS(143),
    [sym_string] = ACTIONS(143),
    [sym_verbatim_string] = ACTIONS(143),
    [sym_quoted_identifier] = ACTIONS(143),
    [sym_directive] = ACTIONS(143),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(145),
    [sym_punctuation] = ACTIONS(143),
    [sym_keyword] = ACTIONS(143),
    [sym_control_keyword] = ACTIONS(143),
    [sym_object_keyword] = ACTIONS(143),
    [sym_type_keyword] = ACTIONS(143),
    [sym_metadata_keyword] = ACTIONS(143),
    [sym_property_keyword] = ACTIONS(143),
  },
  [STATE(34)] = {
    [sym_identifier] = ACTIONS(159),
    [anon_sym_LBRACE] = ACTIONS(159),
    [anon_sym_LPAREN] = ACTIONS(159),
    [anon_sym_LBRACK] = ACTIONS(159),
    [sym_integer] = ACTIONS(159),
    [sym_string] = ACTIONS(159),
    [sym_verbatim_string] = ACTIONS(159),
    [sym_quoted_identifier] = ACTIONS(159),
    [sym_directive] = ACTIONS(159),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(161),
    [sym_punctuation] = ACTIONS(159),
    [sym_keyword] = ACTIONS(159),
    [sym_control_keyword] = ACTIONS(159),
    [sym_object_keyword] = ACTIONS(159),
    [sym_type_keyword] = ACTIONS(159),
    [sym_metadata_keyword] = ACTIONS(159),
    [sym_property_keyword] = ACTIONS(159),
  },
  [STATE(35)] = {
    [sym_identifier] = ACTIONS(155),
    [anon_sym_LBRACE] = ACTIONS(155),
    [anon_sym_LPAREN] = ACTIONS(155),
    [anon_sym_LBRACK] = ACTIONS(155),
    [sym_integer] = ACTIONS(155),
    [sym_string] = ACTIONS(155),
    [sym_verbatim_string] = ACTIONS(155),
    [sym_quoted_identifier] = ACTIONS(155),
    [sym_directive] = ACTIONS(155),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(157),
    [sym_punctuation] = ACTIONS(155),
    [sym_keyword] = ACTIONS(155),
    [sym_control_keyword] = ACTIONS(155),
    [sym_object_keyword] = ACTIONS(155),
    [sym_type_keyword] = ACTIONS(155),
    [sym_metadata_keyword] = ACTIONS(155),
    [sym_property_keyword] = ACTIONS(155),
  },
  [STATE(36)] = {
    [sym_identifier] = ACTIONS(195),
    [anon_sym_LBRACE] = ACTIONS(195),
    [anon_sym_LPAREN] = ACTIONS(195),
    [anon_sym_LBRACK] = ACTIONS(195),
    [sym_integer] = ACTIONS(195),
    [sym_string] = ACTIONS(195),
    [sym_verbatim_string] = ACTIONS(195),
    [sym_quoted_identifier] = ACTIONS(195),
    [sym_directive] = ACTIONS(195),
    [sym_comment] = ACTIONS(5),
    [sym_operator] = ACTIONS(197),
    [sym_punctuation] = ACTIONS(195),
    [sym_keyword] = ACTIONS(195),
    [sym_control_keyword] = ACTIONS(195),
    [sym_object_keyword] = ACTIONS(195),
    [sym_type_keyword] = ACTIONS(195),
    [sym_metadata_keyword] = ACTIONS(195),
    [sym_property_keyword] = ACTIONS(195),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    STATE(32), 1,
      sym_name,
    ACTIONS(3), 2,
      sym_directive,
      sym_comment,
    ACTIONS(169), 2,
      sym_identifier,
      sym_quoted_identifier,
  [12] = 3,
    STATE(14), 1,
      sym_name,
    ACTIONS(3), 2,
      sym_directive,
      sym_comment,
    ACTIONS(169), 2,
      sym_identifier,
      sym_quoted_identifier,
  [24] = 2,
    ACTIONS(199), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_directive,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(37)] = 0,
  [SMALL_STATE(38)] = 12,
  [SMALL_STATE(39)] = 24,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_block_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_braced_block_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_block_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_braced_block_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_braced_block_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [110] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [114] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_object_declaration_repeat1, 2, 0, 0),
  [131] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_object_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_object_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_block, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_block, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracketed_block, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracketed_block, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_block, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_block, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracketed_block, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracketed_block, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_block, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_block, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_braced_block, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_braced_block, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__atom, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__atom, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_declaration, 3, 0, 1),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_declaration, 3, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_declaration, 5, 0, 5),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_declaration, 5, 0, 5),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_declaration, 4, 0, 4),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_declaration, 4, 0, 4),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_declaration, 4, 0, 2),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_declaration, 4, 0, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_modifier, 2, 0, 3),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_modifier, 2, 0, 3),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_name, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_keyword = 0,
  ts_external_token_control_keyword = 1,
  ts_external_token_object_keyword = 2,
  ts_external_token_type_keyword = 3,
  ts_external_token_metadata_keyword = 4,
  ts_external_token_property_keyword = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_keyword] = sym_keyword,
  [ts_external_token_control_keyword] = sym_control_keyword,
  [ts_external_token_object_keyword] = sym_object_keyword,
  [ts_external_token_type_keyword] = sym_type_keyword,
  [ts_external_token_metadata_keyword] = sym_metadata_keyword,
  [ts_external_token_property_keyword] = sym_property_keyword,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_keyword] = true,
    [ts_external_token_control_keyword] = true,
    [ts_external_token_object_keyword] = true,
    [ts_external_token_type_keyword] = true,
    [ts_external_token_metadata_keyword] = true,
    [ts_external_token_property_keyword] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_al_external_scanner_create(void);
void tree_sitter_al_external_scanner_destroy(void *);
bool tree_sitter_al_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_al_external_scanner_serialize(void *, char *);
void tree_sitter_al_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_al(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_al_external_scanner_create,
      tree_sitter_al_external_scanner_destroy,
      tree_sitter_al_external_scanner_scan,
      tree_sitter_al_external_scanner_serialize,
      tree_sitter_al_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "al",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
