// External Scanner for AL Tree-Sitter
// AUTO-GENERATED - DO NOT EDIT
// Generated by: cargo run

#include <tree_sitter/parser.h>
#include <ctype.h>

// NOTE: tree-sitter only compiles src/scanner.c by default.
// We include the generated keyword lookup directly so no extra build config is needed.
#include "keywords.c"

typedef enum {
  KEYWORD,
  CONTROL_KEYWORD,
  OBJECT_KEYWORD,
  TYPE_KEYWORD,
  METADATA_KEYWORD,
  PROPERTY_KEYWORD,
} TokenType;

void *tree_sitter_al_external_scanner_create() {
  return NULL;
}

void tree_sitter_al_external_scanner_destroy(void *payload) {
  (void)payload;
}

unsigned tree_sitter_al_external_scanner_serialize(void *payload, char *buffer) {
  (void)payload;
  (void)buffer;
  return 0;
}

void tree_sitter_al_external_scanner_deserialize(void *payload, const char *buffer, unsigned length) {
  (void)payload;
  (void)buffer;
  (void)length;
}

static bool scan_word(TSLexer *lexer, char *out, int out_cap) {
  // Skip whitespace
  while (lexer->lookahead == ' ' || lexer->lookahead == '\t' || lexer->lookahead == '\r' || lexer->lookahead == '\n') {
    lexer->advance(lexer, true);
  }

  // Must start with letter or underscore
  int32_t c = lexer->lookahead;
  if (!(c == '_' || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z'))) {
    return false;
  }

  int len = 0;
  while (len < out_cap - 1) {
    int32_t ch = lexer->lookahead;
    if (ch == '_' ||
        (ch >= 'A' && ch <= 'Z') ||
        (ch >= 'a' && ch <= 'z') ||
        (ch >= '0' && ch <= '9')) {
      out[len++] = (char)tolower((unsigned char)ch);
      lexer->advance(lexer, false);
      continue;
    }
    break;
  }
  out[len] = '\0';
  lexer->mark_end(lexer);
  return true;
}

bool tree_sitter_al_external_scanner_scan(void *payload, TSLexer *lexer, const bool *valid_symbols) {
  (void)payload;

  // Fast-path: if no keyword-like tokens are valid in this state, don't scan.
  if (!valid_symbols[KEYWORD] &&
      !valid_symbols[CONTROL_KEYWORD] &&
      !valid_symbols[OBJECT_KEYWORD] &&
      !valid_symbols[TYPE_KEYWORD] &&
      !valid_symbols[METADATA_KEYWORD] &&
      !valid_symbols[PROPERTY_KEYWORD]) {
    return false;
  }

  char word[256];
  if (!scan_word(lexer, word, (int)sizeof(word))) {
    return false;
  }

  // Prefer the most context-specific token that is valid in this parse state.
  // IMPORTANT: Some words exist in multiple categories (e.g. "array").
  // We only return categories that are valid in the current state.
  if (valid_symbols[CONTROL_KEYWORD] && is_al_control_keyword(word)) {
    lexer->result_symbol = CONTROL_KEYWORD;
    return true;
  }
  if (valid_symbols[OBJECT_KEYWORD] && is_al_object_keyword(word)) {
    lexer->result_symbol = OBJECT_KEYWORD;
    return true;
  }
  if (valid_symbols[TYPE_KEYWORD] && is_al_type_keyword(word)) {
    lexer->result_symbol = TYPE_KEYWORD;
    return true;
  }
  if (valid_symbols[METADATA_KEYWORD] && is_al_metadata_keyword(word)) {
    lexer->result_symbol = METADATA_KEYWORD;
    return true;
  }
  if (valid_symbols[PROPERTY_KEYWORD] && is_al_property_keyword(word)) {
    lexer->result_symbol = PROPERTY_KEYWORD;
    return true;
  }
  if (valid_symbols[KEYWORD] && is_al_keyword(word)) {
    lexer->result_symbol = KEYWORD;
    return true;
  }

  return false;
}
